project:
  type: website
  output-dir: docs

website:
  title: "jeandelmotte.com"
  page-navigation: true
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/propan2one
      - icon: twitter
        href: https://twitter.com/DrStagiaire
      - icon: mastodon
        href: https://genomic.social/@jeandelmotte
    left:
      - text: "Home ğŸ’»"
        href: index.qmd
      - text: "About ğŸ§¬"
        href: about.qmd
      - text: "Post ğŸ“š"
        href: homepage.qmd
      - text: "Contact ğŸ‘¨â€ğŸ”¬"
        href: contact.qmd
  page-footer: 
    left: "Copyright 2024, Delmotte Jean"
    right: 
      - icon: github
        href: https://github.com/propan2one
      - icon: twitter
        href: https://twitter.com/DrStagiaire
      - icon: mastodon
        href: https://genomic.social/@jeandelmotte
format:
  html:
    theme: 
      light: [flatly, custom.scss]
      dark: darkly
    css: styles.css
